# Generated by Django 4.0.6 on 2022-12-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=range(1, 3), max_length=200, unique=True),
        ),
    ]
